name: Package Addon

on:
  schedule:
    - cron: "0 1 * * *"  # Run once a day at 1am
  workflow_dispatch:  # Allow manual runs

jobs:
  package-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Mirror Repo
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Step 1: Fetch tags from PetTracker
      - name: Fetch tags from PetTracker
        run: |
          git fetch --tags https://github.com/Jaliborc/PetTracker.git

      # Step 2: Get the latest tag from PetTracker
      - name: Get the latest tag from PetTracker
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) --abbrev=0)
          echo "Latest tag in PetTracker: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      # Step 3: Check if new release tag exists
      - name: Check if new release tag exists
        id: check_new_tag
        run: |
          if [ "$latest_tag" == "${{ secrets.LAST_TAG }}" ]; then
            echo "No new tag, skipping package creation."
            exit 0
          else
            echo "New tag detected: $latest_tag"
            echo "LAST_TAG=$latest_tag" >> $GITHUB_ENV
          fi

      # Step 4: Package WoW Addon if new tag
      - name: Package WoW Addon
        if: steps.check_new_tag.outcome == 'success'
        run: |
          cd PetTracker
          zip -r PetTracker.zip PetTracker/*

      # Step 5: Push the .zip file to Mirror Repo
      - name: Push Addon Package to Mirror Repo
        if: steps.check_new_tag.outcome == 'success'
        run: |
          cd PetTracker
          git add PetTracker.zip
          git commit -m "Add new WoW addon package for tag ${{ env.latest_tag }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/andi-74/pettracker-mirror.git master
